.

diff --git a/infrastructure/ci-cd-pipeline.yml b/infrastructure/ci-cd-pipeline.yml
--- a/infrastructure/ci-cd-pipeline.yml
+++ b/infrastructure/ci-cd-pipeline.yml
@@ -96,20 +96,18 @@ jobs:
   dependsOn:
   - Terraform_shared_outputs
   variables:
-    KUBE_CONFIG_RAW: $[ dependencies.Terraform_shared_outputs.outputs['Outputs.kube_config_raw'] ]
+    KUBE_CONFIG_BASE64: $[ dependencies.Terraform_shared_outputs.outputs['Outputs.kube_config_base64'] ]
     KUSTO_NAME: $[ dependencies.Terraform_shared_outputs.outputs['Outputs.kusto_name'] ]
     TERRAFORM_DIRECTORY: infrastructure/terraform-specific
   steps:
 
   - bash: |
-      set -eux  # fail on error
-      echo "$KUBE_CONFIG_RAW" | perl -pe 's/\\n/\n/g' > kube_config
-      #FIXME
-      cat kube_config
+      set -eu  # fail on error
+      base64 -d <<< $KUBE_CONFIG_BASE64 > kube_config
       echo "##vso[task.setvariable variable=KUBECONFIG]$PWD/kube_config"
     displayName: Save kubeconfig
     env:
-      KUBE_CONFIG_RAW: $(KUBE_CONFIG_RAW)
+      KUBE_CONFIG_BASE64: $(KUBE_CONFIG_BASE64)
 
   - bash: |
       set -eu  # fail on error
@@ -306,7 +304,17 @@ jobs:
   - build
   - Terraform_specific
   - Terraform_shared_outputs
+  variables:
+    KUBE_CONFIG_BASE64: $[ dependencies.Terraform_shared_outputs.outputs['Outputs.kube_config_base64'] ]
   steps:
+
+  - bash: |
+      set -eu  # fail on error
+      base64 -d <<< $KUBE_CONFIG_BASE64 > kube_config
+      echo "##vso[task.setvariable variable=KUBECONFIG]$PWD/kube_config"
+    displayName: Save kubeconfig
+    env:
+      KUBE_CONFIG_BASE64: $(KUBE_CONFIG_BASE64)
 
   - template: setup-k8s-clients-template.yml
 
