Update terraform-apply-template.yml

diff --git a/infrastructure/terraform-apply-template.yml b/infrastructure/terraform-apply-template.yml
--- a/infrastructure/terraform-apply-template.yml
+++ b/infrastructure/terraform-apply-template.yml
@@ -18,13 +18,12 @@ parameters:
 steps:
 
 - bash: |
-    printenv|sort
-    if [ "$KUBE_CONFIG_BASE64" != "" ]; then
-      set -eu  # fail on error
-      base64 -d <<< $KUBE_CONFIG_BASE64 > kube_config
-      echo "##vso[task.setvariable variable=KUBECONFIG]$PWD/kube_config"
+    set -eu  # fail on error
+    base64 -d <<< $KUBE_CONFIG_BASE64 > kube_config
+    echo "##vso[task.setvariable variable=KUBECONFIG]$PWD/kube_config"
     fi
   displayName: Save kubeconfig
+  condition: ne(variables.KUBE_CONFIG_BASE64, '')
   env:
     KUBE_CONFIG_BASE64: $(KUBE_CONFIG_BASE64)
 
